FROM python:3.12.2

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application
COPY mqttclone.py .

# Run the application
CMD ["python", "-u", "mqttclone.py"]